# Generated by Django 5.0.6 on 2024-07-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patcher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandingPageStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('description', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'ordering': ['description'],
            },
        ),
    ]
